### ISSUE TITLE
Chat-Engine-Vue demo and tutorial only getting 404 on connect

### ISSUE THREAD

**Issue by laneelliott** [ajb413/chat-engine-vue#3]
I've gone through the official Vue Chat Engine installation guide and the official tutorial, found [here](https://www.pubnub.com/blog/introducing-the-chatengine-plugin-for-vue/). I've also forked this github repo as well and every single attempt at running this plugin results in a 404 with pubnub on ChatEngine.connect(me.uuid, me); I know this is a new product but could you please look into this issue and advise/fix the code or installation instructions to get this to work. 

Here is an example of the error I'm getting back. 
![image](https://user-images.githubusercontent.com/20445046/41011182-4513cdf8-6901-11e8-9831-3915c9faa5dd.png)

Here is the code I'm using.
```
//main.js
import Vue from 'vue'
import App from './App'
import router from './router'
import store from './store'
import VueChatEngine from 'vue-chat-engine';
import ChatEngineCore from 'chat-engine';

import './scss/index.scss' // Global SCSS Stylesheet

Vue.config.productionTip = false

const chatEngine = ChatEngineCore.create({
  publishKey: '--publishkey--',
  subscribeKey: '--subscribekey--'
}, {
    globalChannel: 'chatengine-vue-demo-global',
    enableSync: true,
  });

// ChatEngine injected into every component instance
Vue.use(VueChatEngine, { chatEngine, store });

/* eslint-disable no-new */
new Vue({
  el: '#app',
  router,
  store,
  components: { App },
  template: '<App/>',
  created() {
    const ChatEngine = this.$chatEngine;
    const store = this.$store;
    ChatEngine.connect('123456789', {team: 'red'});
  }
})
```

```
//store.js
import Vue from 'vue'
import Vuex from 'vuex'

Vue.use(Vuex)

export default new Vuex.Store({
    state: {
        chats: {},
        chatMessages: [],
        emojis: [],
    },
    getters: {
        messageQue: function(state) {
            return state.chatMessages
        },
        emojiQue: function (state) {
            return state.emojis
        }
    },
    mutations: {
        addMessage: function(state, message) {
            state.chatMessages.push(message);
        },
        addEmoji: function (state, emoji) {
            state.emojis.push(emoji);
        },
        setMe(state, { me }) {
            state.me = me;
        },
        CHATENGINE_message(state, { event, sender, chat, data }) {
            let channel = chat.config.channel;

            if (!state.chatMessages[channel]) {
                Vue.set(state.chatMessages, channel, []);
            }

            let myUuid = this.state.me.uuid;
            let message = data;

            if (sender.uuid === myUuid) {
                message.who = 'me';
            } else {
                message.who = 'them';
            }

            state.chatMessages[channel].push(message);
            state.chatMessages[channel].sort((msg1, msg2) => {
                return msg1.time > msg2.time;
            });
        },
    },
    actions: {
    
    }
});

```
Thank you in advance for looking into this.

**Comment by ajb413** [comment]
Hi! I did not see the GitHub issue alert for this, sorry for the late reply.

A 404 like you experienced happens in 2 situations:

- If you have not already, you need to press the [ChatEngine Deploy button](https://www.pubnub.com/tutorials/chatengine/?devrel_gh=chat-engine-vue) from the Quickstart. It gives you a new Publish and Subscribe key set. This globally deploys your serverless endpoints using PubNub Functions on the new key set. Use the new keys that are generated in your ChatEngine front-end app code. This is 100% free by the way.

![alt text][button](https://www.pubnub.com/tutorials/chatengine/?devrel_gh=chat-engine-vue)

[button]: https://i.imgur.com/KOl373p.png "ChatEngine Button"



- When you use a [Free PubNub Account](https://www.pubnub.com/pricing/?devrel_gh=chat-engine-vue), and there is no messaging activity for 7 days on the app, your PubNub Functions are paused. You will need to restart the Function in the [PubNub Admin Dashboard](https://dashboard.pubnub.com/login?devrel_gh=chat-engine-vue).

![alt text][button-functions]

[button-functions]: https://i.imgur.com/zrM17ex.png "Functions Restart Button"
